const data = () => {
  return {
    data: {
      villagers: [],
      isOpen: false,
      currentVillager: {},
    },
    init() {
      fetch('https://acnhapi.com/v1/villagers')
        .then((res) => {
          return res.json();
        })
        .then((data) => {
          console.log(Object.values(data));
          this.data.villagers = Object.values(data);
        });
    },
  };

  // const staticVillagerData = () => {
  //   return {
  //     ant00: {
  //       id: 1,
  //       'file-name': 'ant00',
  //       name: {
  //         'name-USen': 'Cyrano',
  //         'name-EUen': 'Cyrano',
  //         'name-EUde': 'Theo',
  //         'name-EUes': 'Cirano',
  //         'name-USes': 'Cirano',
  //         'name-EUfr': 'Cyrano',
  //         'name-USfr': 'Cyrano',
  //         'name-EUit': 'Cirano',
  //         'name-EUnl': 'Cyrano',
  //         'name-CNzh': '阳明',
  //         'name-TWzh': '陽明',
  //         'name-JPja': 'さくらじま',
  //         'name-KRko': '사지마',
  //         'name-EUru': 'Сирано',
  //       },
  //       personality: 'Cranky',
  //       'birthday-string': 'March 9th',
  //       birthday: '9/3',
  //       species: 'Anteater',
  //       gender: 'Male',
  //       subtype: 'B',
  //       hobby: 'Education',
  //       'catch-phrase': 'ah-CHOO',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/1',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/1',
  //       'bubble-color': '#194c89',
  //       'text-color': '#fffad4',
  //       saying: "Don't punch your nose to spite your face.",
  //       'catch-translations': {
  //         'catch-USen': 'ah-CHOO',
  //         'catch-EUen': 'ah-CHOO',
  //         'catch-EUde': 'schneuf',
  //         'catch-EUes': 'achús',
  //         'catch-USes': 'achús',
  //         'catch-EUfr': 'ATCHOUM',
  //         'catch-USfr': 'ATCHOUM',
  //         'catch-EUit': 'ett-CCIÙ',
  //         'catch-EUnl': 'ha-TSJOE',
  //         'catch-CNzh': '有的',
  //         'catch-TWzh': '有的',
  //         'catch-JPja': 'でごわす',
  //         'catch-KRko': '임돠',
  //         'catch-EUru': 'апчхи',
  //       },
  //     },
  //     ant01: {
  //       id: 2,
  //       'file-name': 'ant01',
  //       name: {
  //         'name-USen': 'Antonio',
  //         'name-EUen': 'Antonio',
  //         'name-EUde': 'Siggi',
  //         'name-EUes': 'Antonio',
  //         'name-USes': 'Antonio',
  //         'name-EUfr': 'Antonio',
  //         'name-USfr': 'Antonio',
  //         'name-EUit': 'Antonio',
  //         'name-EUnl': 'Antonio',
  //         'name-CNzh': '阿诚',
  //         'name-TWzh': '阿誠',
  //         'name-JPja': 'マコト',
  //         'name-KRko': '퍼머거',
  //         'name-EUru': 'Антонио',
  //       },
  //       personality: 'Jock',
  //       'birthday-string': 'October 20th',
  //       birthday: '20/10',
  //       species: 'Anteater',
  //       gender: 'Male',
  //       subtype: 'B',
  //       hobby: 'Fitness',
  //       'catch-phrase': 'honk',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/2',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/2',
  //       'bubble-color': '#fff98f',
  //       'text-color': '#879b96',
  //       saying: 'Always go for the burn!',
  //       'catch-translations': {
  //         'catch-USen': 'honk',
  //         'catch-EUen': 'honk',
  //         'catch-EUde': 'schlürrrf',
  //         'catch-EUes': 'fufuf',
  //         'catch-USes': 'fufuf',
  //         'catch-EUfr': 'pouet',
  //         'catch-USfr': 'pouet',
  //         'catch-EUit': 'honk',
  //         'catch-EUnl': 'snuit',
  //         'catch-CNzh': '真诚',
  //         'catch-TWzh': '真誠',
  //         'catch-JPja': 'ホントに',
  //         'catch-KRko': '진짜로',
  //         'catch-EUru': 'го-го-го',
  //       },
  //     },
  //     ant02: {
  //       id: 3,
  //       'file-name': 'ant02',
  //       name: {
  //         'name-USen': 'Pango',
  //         'name-EUen': 'Pango',
  //         'name-EUde': 'Mathilda',
  //         'name-EUes': 'Aspidora',
  //         'name-USes': 'Aspidora',
  //         'name-EUfr': 'Mathilda',
  //         'name-USfr': 'Mathilda',
  //         'name-EUit': 'Carlotta',
  //         'name-EUnl': 'Pango',
  //         'name-CNzh': '佩希',
  //         'name-TWzh': '佩希',
  //         'name-JPja': 'パトラ',
  //         'name-KRko': '패트라',
  //         'name-EUru': 'Панго',
  //       },
  //       personality: 'Peppy',
  //       'birthday-string': 'November 9th',
  //       birthday: '9/11',
  //       species: 'Anteater',
  //       gender: 'Female',
  //       subtype: 'B',
  //       hobby: 'Fashion',
  //       'catch-phrase': 'snooooof',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/3',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/3',
  //       'bubble-color': '#00d1bd',
  //       'text-color': '#fffce9',
  //       saying: 'A thing of beauty is a joy forever.',
  //       'catch-translations': {
  //         'catch-USen': 'snooooof',
  //         'catch-EUen': 'snooooof',
  //         'catch-EUde': 'schnieef',
  //         'catch-EUes': 'snuf-snuf',
  //         'catch-USes': 'snuf-snuf',
  //         'catch-EUfr': 'pouuuuuf',
  //         'catch-USfr': 'pouuuuuf',
  //         'catch-EUit': 'snuuf',
  //         'catch-EUnl': 'snufffff',
  //         'catch-CNzh': '希希',
  //         'catch-TWzh': '希希',
  //         'catch-JPja': 'だっしー',
  //         'catch-KRko': '라지요',
  //         'catch-EUru': 'снуф-снуф',
  //       },
  //     },
  //     ant03: {
  //       id: 4,
  //       'file-name': 'ant03',
  //       name: {
  //         'name-USen': 'Anabelle',
  //         'name-EUen': 'Anabelle',
  //         'name-EUde': 'Annabell',
  //         'name-EUes': 'Anabel',
  //         'name-USes': 'Anabel',
  //         'name-EUfr': 'Anabelle',
  //         'name-USfr': 'Anabelle',
  //         'name-EUit': 'Annalisa',
  //         'name-EUnl': 'Anabelle',
  //         'name-CNzh': '有美',
  //         'name-TWzh': '有美',
  //         'name-JPja': 'あるみ',
  //         'name-KRko': '아롱이',
  //         'name-EUru': 'Анабель',
  //       },
  //       personality: 'Peppy',
  //       'birthday-string': 'February 16th',
  //       birthday: '16/2',
  //       species: 'Anteater',
  //       gender: 'Female',
  //       subtype: 'B',
  //       hobby: 'Fashion',
  //       'catch-phrase': 'snorty',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/4',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/4',
  //       'bubble-color': '#ff791f',
  //       'text-color': '#fff2bb',
  //       saying: "Dance like no one's watching!",
  //       'catch-translations': {
  //         'catch-USen': 'snorty',
  //         'catch-EUen': 'snorty',
  //         'catch-EUde': 'puuust',
  //         'catch-EUes': 'esnoink',
  //         'catch-USes': 'fa-fiú',
  //         'catch-EUfr': 'grognon',
  //         'catch-USfr': 'grognon',
  //         'catch-EUit': 'snorty',
  //         'catch-EUnl': 'snork',
  //         'catch-CNzh': '真的假的',
  //         'catch-TWzh': '真的假的',
  //         'catch-JPja': 'マジでー',
  //         'catch-KRko': '정말',
  //         'catch-EUru': 'хрум-хрум',
  //       },
  //     },
  //     ant06: {
  //       id: 5,
  //       'file-name': 'ant06',
  //       name: {
  //         'name-USen': 'Snooty',
  //         'name-EUen': 'Snooty',
  //         'name-EUde': 'Hilde',
  //         'name-EUes': 'Rosanari',
  //         'name-USes': 'Rosanari',
  //         'name-EUfr': 'Tarina',
  //         'name-USfr': 'Tarina',
  //         'name-EUit': 'Lucrezia',
  //         'name-EUnl': 'Snooty',
  //         'name-CNzh': '贵妃',
  //         'name-TWzh': '貴妃',
  //         'name-JPja': 'こまち',
  //         'name-KRko': '스누티',
  //         'name-EUru': 'Снути',
  //       },
  //       personality: 'Snooty',
  //       'birthday-string': 'October 24th',
  //       birthday: '24/10',
  //       species: 'Anteater',
  //       gender: 'Female',
  //       subtype: 'A',
  //       hobby: 'Education',
  //       'catch-phrase': 'sniffff',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/5',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/5',
  //       'bubble-color': '#f2bdc7',
  //       'text-color': '#634b4b',
  //       saying: 'Request forgiveness, not permission.',
  //       'catch-translations': {
  //         'catch-USen': 'sniffff',
  //         'catch-EUen': 'sniffff',
  //         'catch-EUde': 'schnuff',
  //         'catch-EUes': 'sniff',
  //         'catch-USes': 'sniff',
  //         'catch-EUfr': 'snif snif',
  //         'catch-USfr': 'snif snif',
  //         'catch-EUit': 'sniffff',
  //         'catch-EUnl': 'snuifff',
  //         'catch-CNzh': '麻烦了',
  //         'catch-TWzh': '麻煩了',
  //         'catch-JPja': 'たもれ',
  //         'catch-KRko': '추릅',
  //         'catch-EUru': 'шмыг',
  //       },
  //     },
  //     ant08: {
  //       id: 6,
  //       'file-name': 'ant08',
  //       name: {
  //         'name-USen': 'Annalisa',
  //         'name-EUen': 'Annalisa',
  //         'name-EUde': 'Annalena',
  //         'name-EUes': 'Alba',
  //         'name-USes': 'Alba',
  //         'name-EUfr': 'Roberta',
  //         'name-USfr': 'Roberta',
  //         'name-EUit': 'Anita',
  //         'name-EUnl': 'Annalisa',
  //         'name-CNzh': '小雅',
  //         'name-TWzh': '小雅',
  //         'name-JPja': 'みやび',
  //         'name-KRko': '설백',
  //         'name-EUru': 'Аннализа',
  //       },
  //       personality: 'Normal',
  //       'birthday-string': 'February 6th',
  //       birthday: '6/2',
  //       species: 'Anteater',
  //       gender: 'Female',
  //       subtype: 'A',
  //       hobby: 'Nature',
  //       'catch-phrase': 'gumdrop',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/6',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/6',
  //       'bubble-color': '#ffffff',
  //       'text-color': '#848484',
  //       saying: 'Home is where the heart is.',
  //       'catch-translations': {
  //         'catch-USen': 'gumdrop',
  //         'catch-EUen': 'gumdrop',
  //         'catch-EUde': 'schnüffel',
  //         'catch-EUes': 'nubecillas',
  //         'catch-USes': 'snifffi',
  //         'catch-EUfr': 'tap tap',
  //         'catch-USfr': 'tap tap',
  //         'catch-EUit': 'chic',
  //         'catch-EUnl': 'dropje',
  //         'catch-CNzh': '优雅',
  //         'catch-TWzh': '優雅',
  //         'catch-JPja': 'をかし',
  //         'catch-KRko': '하양하양',
  //         'catch-EUru': 'жуй-жуй',
  //       },
  //     },
  //     ant09: {
  //       id: 7,
  //       'file-name': 'ant09',
  //       name: {
  //         'name-USen': 'Olaf',
  //         'name-EUen': 'Olaf',
  //         'name-EUde': 'Olaf',
  //         'name-EUes': 'Olaf',
  //         'name-USes': 'Olaf',
  //         'name-EUfr': 'Blair',
  //         'name-USfr': 'Blair',
  //         'name-EUit': 'Ettore',
  //         'name-EUnl': 'Olaf',
  //         'name-CNzh': '安东尼',
  //         'name-TWzh': '安東尼',
  //         'name-JPja': 'アントニオ',
  //         'name-KRko': '안토니오',
  //         'name-EUru': 'Олаф',
  //       },
  //       personality: 'Smug',
  //       'birthday-string': 'May 19th',
  //       birthday: '19/5',
  //       species: 'Anteater',
  //       gender: 'Male',
  //       subtype: 'A',
  //       hobby: 'Education',
  //       'catch-phrase': 'whiffa',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/7',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/7',
  //       'bubble-color': '#ff791f',
  //       'text-color': '#fff2bb',
  //       saying: 'Keep your nose clean.',
  //       'catch-translations': {
  //         'catch-USen': 'whiffa',
  //         'catch-EUen': 'whiffa',
  //         'catch-EUde': 'mwahaaa',
  //         'catch-EUes': 'fruf',
  //         'catch-USes': 'fruf',
  //         'catch-EUfr': 'tartarin',
  //         'catch-USfr': 'yesss',
  //         'catch-EUit': 'swish',
  //         'catch-EUnl': 'toet',
  //         'catch-CNzh': '欧啦',
  //         'catch-TWzh': '歐啦',
  //         'catch-JPja': 'ムーチョ',
  //         'catch-KRko': '무쵸',
  //         'catch-EUru': 'уф-уф',
  //       },
  //     },
  //     bea00: {
  //       id: 8,
  //       'file-name': 'bea00',
  //       name: {
  //         'name-USen': 'Teddy',
  //         'name-EUen': 'Teddy',
  //         'name-EUde': 'Torsten',
  //         'name-EUes': 'Teddy',
  //         'name-USes': 'Teddy',
  //         'name-EUfr': 'Teddy',
  //         'name-USfr': 'Teddy',
  //         'name-EUit': 'Teddy',
  //         'name-EUnl': 'Teddy',
  //         'name-CNzh': '太平',
  //         'name-TWzh': '太平',
  //         'name-JPja': 'たいへいた',
  //         'name-KRko': '병태',
  //         'name-EUru': 'Тедди',
  //       },
  //       personality: 'Jock',
  //       'birthday-string': 'September 26th',
  //       birthday: '26/9',
  //       species: 'Bear',
  //       gender: 'Male',
  //       subtype: 'B',
  //       hobby: 'Fitness',
  //       'catch-phrase': 'grooof',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/8',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/8',
  //       'bubble-color': '#ff791f',
  //       'text-color': '#fff2bb',
  //       saying: 'No pain, no gain!',
  //       'catch-translations': {
  //         'catch-USen': 'grooof',
  //         'catch-EUen': 'grooof',
  //         'catch-EUde': 'gruff',
  //         'catch-EUes': 'gruuuf',
  //         'catch-USes': 'gruuuf',
  //         'catch-EUfr': 'grrrrrr',
  //         'catch-USfr': 'grrrrrr',
  //         'catch-EUit': 'gruf',
  //         'catch-EUnl': 'grommm',
  //         'catch-CNzh': '太好了',
  //         'catch-TWzh': '太好了',
  //         'catch-JPja': 'ですたい',
  //         'catch-KRko': '입네다',
  //         'catch-EUru': 'быр-быр',
  //       },
  //     },
  //     bea01: {
  //       id: 9,
  //       'file-name': 'bea01',
  //       name: {
  //         'name-USen': 'Pinky',
  //         'name-EUen': 'Pinky',
  //         'name-EUde': 'Pia',
  //         'name-EUes': 'Violeta',
  //         'name-USes': 'Violeta',
  //         'name-EUfr': 'Rosine',
  //         'name-USfr': 'Rosine',
  //         'name-EUit': 'Pinky',
  //         'name-EUnl': 'Pinky',
  //         'name-CNzh': '丹丹',
  //         'name-TWzh': '丹丹',
  //         'name-JPja': 'タンタン',
  //         'name-KRko': '링링',
  //         'name-EUru': 'Пинки',
  //       },
  //       personality: 'Peppy',
  //       'birthday-string': 'September 9th',
  //       birthday: '9/9',
  //       species: 'Bear',
  //       gender: 'Female',
  //       subtype: 'B',
  //       hobby: 'Fashion',
  //       'catch-phrase': 'wah',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/9',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/9',
  //       'bubble-color': '#fff98f',
  //       'text-color': '#879b96',
  //       saying: 'Time spent with friends is time well spent.',
  //       'catch-translations': {
  //         'catch-USen': 'wah',
  //         'catch-EUen': 'wah',
  //         'catch-EUde': 'schätzchen',
  //         'catch-EUes': 'terronillo',
  //         'catch-USes': 'guah',
  //         'catch-EUfr': 'ouah',
  //         'catch-USfr': 'ouah',
  //         'catch-EUit': 'cubetto',
  //         'catch-EUnl': 'wauw',
  //         'catch-CNzh': '哇喔',
  //         'catch-TWzh': '哇喔',
  //         'catch-JPja': 'わぉ',
  //         'catch-KRko': '와',
  //         'catch-EUru': 'ну и ну',
  //       },
  //     },
  //     bea02: {
  //       id: 10,
  //       'file-name': 'bea02',
  //       name: {
  //         'name-USen': 'Curt',
  //         'name-EUen': 'Curt',
  //         'name-EUde': 'Kurt',
  //         'name-EUes': 'Gorbaché',
  //         'name-USes': 'Gorbaché',
  //         'name-EUfr': 'Curt',
  //         'name-USfr': 'Curt',
  //         'name-EUit': 'Curt',
  //         'name-EUnl': 'Curt',
  //         'name-CNzh': '铁熊',
  //         'name-TWzh': '鐵熊',
  //         'name-JPja': 'ガンテツ',
  //         'name-KRko': '뚝심',
  //         'name-EUru': 'Керт',
  //       },
  //       personality: 'Cranky',
  //       'birthday-string': 'July 1st',
  //       birthday: '1/7',
  //       species: 'Bear',
  //       gender: 'Male',
  //       subtype: 'A',
  //       hobby: 'Nature',
  //       'catch-phrase': 'fuzzball',
  //       icon_uri: 'https://acnhapi.com/v1/icons/villagers/10',
  //       image_uri: 'https://acnhapi.com/v1/images/villagers/10',
  //       'bubble-color': '#515151',
  //       'text-color': '#fffce9',
  //       saying: 'A Bell saved is a Bell earned.',
  //       'catch-translations': {
  //         'catch-USen': 'fuzzball',
  //         'catch-EUen': 'fuzzball',
  //         'catch-EUde': 'grumml',
  //         'catch-EUes': 'oye',
  //         'catch-USes': 'gromp',
  //         'catch-EUfr': 'bouboule',
  //         'catch-USfr': 'bouboule',
  //         'catch-EUit': 'grrroan',
  //         'catch-EUnl': 'brombeer',
  //         'catch-CNzh': '嗯唔',
  //         'catch-TWzh': '嗯唔',
  //         'catch-JPja': 'ウム',
  //         'catch-KRko': '음',
  //         'catch-EUru': 'махрово',
  //       },
  //     },
  //   };
  // };
};
